module.exports = {
  BJ_dining_pc              : require('./BJ-dining-config'),
  BJ_dining_xcx             : require('./BJ-dining-WeChatApplet-config'),
  shopWeChatApplet_period_20: require('./ShopWeChatApplet-period-20-config'),
  shopWeChatApplet_period_22: require('./ShopWeChatApplet-period-22-config'),
  shopWeChatApplet_period_23: require('./ShopWeChatApplet-period-23-config'),
  shopWeChatApplet_period_24: require('./ShopWeChatApplet-period-24-config'),
  shopWeChatApplet_dev      : require('./ShopWeChatApplet-dev-config'),
  shopXCX                   : require('./shopXCX-config'),
  JJH_PC                    : require('./JJH-PC-config'),
  shopStore_xcx             : require('./ShopStore-WeChatApplet'),
  shopStore_pc              : require('./shopXCX-store-config'),
  shopStore_takeout_xcx     : require('./ShopStore-takeout-WeChatApplet'),
  hnqzf_WeChatApplet        : require('./hnqzf-WeChatApplet'),
  hnqzf_vue                 : require('./hnqzf-vue'),
  whqzf_vue                 : require('./whqzf-vue'),
}